name = "Simple Vanilla+"
author = "Maspo109"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "436071a7b5b61af0c260fae6ec184b7359e5b16d08aad72e8597306f3ee43056"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
