name = "Simply Vanilla+"
author = "Maspo109"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea56e99141684fbe4e6e863eddebb3e0cd93f23b1e83377f74702e77fb11eb7f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
