name = "Simply Vanilla+"
author = "Maspo109"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "435fe4a18b61ff93ef954f9a493820f32eaf194da07b2eea0b80104a1c898750"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
