name: Release Modpack
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install packwiz
        uses: actionhippie/install-packwiz@v1

      - name: Get version
        run: echo version=v$(grep -e "^version" pack.toml | cut -f3 -d' ' | tr -d '"') >> "$GITHUB_OUTPUT"
        id: version

      - name: Run build script
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}

      - name: Upload assets
        uses: csexton/release-asset-action@v3
        with:
          pattern: "build/*.zip"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
