name: Release Modpack
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ "closed" ]
    branches: [ "main" ]

jobs:
  release:
    if: github.event.pull_request.merged || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install packwiz
        uses: actionhippie/install-packwiz@v1

      - name: Get version
        id: version
        run: echo version=v$(grep -e "^version" pack.toml | cut -f3 -d' ' | tr -d '"') >> "$GITHUB_OUTPUT"

      - name: Run build script
        run: |
          chmod +x ./build.sh
          ./build.sh
        
      - name: Create tag
        id: create_tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a -m "Created version tag for ${{ steps.version.outputs.version }}" ${{ steps.version.outputs.version }} ${{ github.sha }}
          git push

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}

      - name: Upload assets
        uses: csexton/release-asset-action@v3
        with:
          pattern: "build/*.zip"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
